# Generated by Django 3.2.16 on 2022-10-26 10:38

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512, unique=True, verbose_name='Наименование')),
                ('description_short', models.CharField(blank=True, max_length=512, null=True, verbose_name='Краткое описание')),
                ('description_long', ckeditor.fields.RichTextField(verbose_name='Полное описание')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
            ],
        ),
    ]
