# Generated by Django 3.2.16 on 2022-10-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20221027_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='places', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='order',
            field=models.IntegerField(blank=True, default=0, verbose_name='Ранг изображения'),
        ),
    ]
