# Generated by Django 3.2.16 on 2022-12-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_placeimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Ранг изображения'),
        ),
    ]
